LOOP-3951: Tweaks skipping onboarding to have two choices: with or without simulators
tidepool-org/TidepoolOnboarding pull request #59
Opened 2022-01-25 00:26 UTC by rickpasetto

Needed this to fix for uitesting

2022-01-25 01:44 UTC, darinkrauss requested changes
Please see comment for requested changes.

2022-01-25 01:44 UTC, darinkrauss commented on TidepoolOnboarding/Views/Sections/WelcomeViews.swift
> +                    onboardingViewModel.skipAllSections(forceSimulators: false)   // NOTE: DEBUG FEATURES - DEBUG AND TEST ONLY
With this change you are requiring folks who use this skip feature to change their behavior. If possible, please flip these changes (so long press on the image does exactly what it did before and a new long press on the text does the new behavior without the simulators).

2022-01-25 18:08 UTC, rickpasetto commented on TidepoolOnboarding/Views/Sections/WelcomeViews.swift
> +                    onboardingViewModel.skipAllSections(forceSimulators: false)   // NOTE: DEBUG FEATURES - DEBUG AND TEST ONLY
@darinkrauss I tried that first, but for some reason `detox` was not able to find the text widget for the long-press, so I opted to move it to the image.  Since this is a debug feature, I presume this isn't a huge deal; I'll update the onboarding doc (which I recommend moving to Confluence, FWIW) and notify everyone on slack (#loop) of this change.

2022-01-26 01:23 UTC, darinkrauss approved these changes
LGTM!

2022-01-26 17:20 UTC, merged